### ISSUE TITLE
No feedback if mirror is misconfigured

### ISSUE THREAD

**Issue by sorenisanerd** [overcastcloud/python-overcast.django#226]
If you misconfigure a mirror, there is no feedback whatsoever. You schedule a refresh and it finishes pretty much immediately. No error. No data. Nothing.

**Comment by mayankkapoor** [comment]
@sorenh Do you mind sharing a proposed/draft implementation approach for this issue? We'll take a look how to fix this.

**Comment by sorenisanerd** [comment]
I suggest we keep a log of e.g. the last 10 apt-mirror runs. So grab the output from the apt-mirror call, store it in a file and make it accessible to end users.
