### ISSUE TITLE
Update django.conf.urls.patterns for Django 1.10

### ISSUE THREAD

**Issue by mayankkapoor** [overcastcloud/python-overcast.django#240]
`/var/lib/pkgbuilder/venv/local/lib/python2.7/site-packages/rest_auth/urls.py:20: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='rest_password_change'),`

**Comment by pljensen** [comment]
This is a django-rest-auth problem, not an aasemble problem.

Oh, and it seems to have been fixed yesterday! Tivix/django-rest-auth#134
