### ISSUE TITLE
Delete button in Sources doesn't work as expected

### ISSUE THREAD

**Issue by manasi24** [overcastcloud/python-overcast.django#26]
**Steps to Reproduce:**
1. Login and Click on Sources.
2. Click on New and give valid inputs for GitURL, branch and  for the dropdown list.
3. Instead of clicking on Submit, click on Delete.

**Expected Outcome:**
The new Package source repository should not be created and the page should be redirected to Sources Page.
**Actual Outcome:**
The new Package source repository is created.

**Note:**
Delete functionality works as expected when the Package Source is already built.
Steps:
1. If the Package Source is already built, and you click on edit icon.
2. In edit, you click on delete, then the repository is deleted properly.

**Comment by sorenisanerd** [comment]
Yeah, there seems to be a problem with the logic in the package_source view in aasemble/django/apps/buildsvc/views.py.

Would you like to work on fixing this?

**Comment by mayankkapoor** [comment]
@manasi24 @sorenh I'll take a look at this issue.
